@startuml

actor ユーザー

boundary handleSubmit
participant LoginController
participant LoginService
participant LoginSession
participant UserRepository
participant User
participant MoneyService
participant MoneyRepository
participant Money
database possession_money
database poker_User_Info

ユーザー -> handleSubmit : ログインボタンをクリック
handleSubmit -> ユーザー : ベット画面にエラー表示
note left : 必須チェックにひっかかった場合
handleSubmit -> LoginController : ログインのためのPOSTリクエスト
LoginController -> LoginService : User login(String username, String password)
LoginService -> UserRepository : Optional<User> getUser(username, password)
UserRepository -> poker_User_Info : SELECT
note left : ユーザー名・パスワードでユーザーが取得できることを確認
LoginService -> LoginController : 取得できない場合、throw LoginFailureException()する
LoginController -> ユーザー : ログイン画面にエラーを表示
LoginService -> User : isLoggedInToday()
note right : 本日ログインしているかどうか確認する
alt ログイン済み
  LoginService -> User : updateLoginTime()
  LoginService -> UserRepository : update(user)
  note right : ログイン日時を更新して保存
  UserRepository -> poker_User_Info : UPDATE
  LoginService -> LoginSession : new(userId)
  note left : ログインセッションを作成
  LoginService -> LoginController : return user
  LoginController -> ユーザー : ポーカースタート画面を表示
else ログイン初めて
  LoginService -> MoneyRepository : getPossession_money(int userId)
  MoneyRepository -> possession_money : SELECT
  LoginService -> Money : void plusMoney(BigDecimal betMoney)
  note right : 100円所持金を増やす
  LoginService -> MoneyRepository : updatepossession_money(Money money)
  MoneyRepository -> possession_money : UPDATE
  LoginService -> User : updateLoginTime()
  LoginService -> UserRepository : update(user)
  note right : ログイン日時を更新して保存
  UserRepository -> poker_User_Info : UPDATE
  LoginService -> LoginSession : new(userId)
  note left : ログインセッションを作成
  LoginService -> LoginController : return user
  LoginController -> ユーザー : ログインサービスにより、\n所持金が増えたことを示すポップアップを表示
end

@enduml