@startuml

boundary ベットリターンAPI
control 所持金情報を更新
control 保存する
control 所持金情報を返却する
entity 所持金

ベットリターンAPI -right- 所持金情報を更新
所持金情報を更新 -- 保存する
保存する -- 所持金情報を返却する
所持金情報を返却する -- ベットリターンAPI

所持金情報を更新 -- 所持金
保存する -- 所持金

@enduml