@startuml

actor ユーザー

boundary ログイン画面
boundary ユーザー登録画面
control パスワードと確認用パスワードが一致しているか確認する
control ユーザー名重複チェックを実施
control エラーを表示する
control 新規ユーザーを作成する
control 保存する
control エラーを表示する
control ログイン画面を表示する
entity 登録済みユーザー一覧
entity 新規ユーザー

'基本コース
ユーザー登録画面 -- ユーザー
ユーザー -- パスワードと確認用パスワードが一致しているか確認する: ユーザー情報を入力して、登録ボタンをクリック
パスワードと確認用パスワードが一致しているか確認する -- ユーザー名重複チェックを実施
ユーザー名重複チェックを実施 -- 新規ユーザーを作成する
新規ユーザーを作成する -- 保存する
保存する -- ログイン画面を表示する
ログイン画面を表示する -- ログイン画面

ユーザー名重複チェックを実施 -- 登録済みユーザー一覧
新規ユーザーを作成する -- 新規ユーザー
保存する -- 新規ユーザー

'代替コース
ユーザー -- ログイン画面を表示する: キャンセルボタンをクリックする
ログイン画面 -- ユーザー

パスワードと確認用パスワードが一致しているか確認する -- エラーを表示する

ユーザー名重複チェックを実施 -- エラーを表示する
エラーを表示する -- ユーザー登録画面



@enduml