@startuml

boundary ユーザー登録API
control ユーザー名重複チェックを実施
control 新規ユーザーを作成する
control 保存する
control ユーザー登録成功を返却する
control ユーザー登録失敗を返却する
entity 登録済みユーザー一覧
entity 新規ユーザー

'基本コース
ユーザー登録API -right- ユーザー名重複チェックを実施
ユーザー名重複チェックを実施 -down- 新規ユーザーを作成する
新規ユーザーを作成する -left- 保存する
保存する -- ユーザー登録成功を返却する
ユーザー登録成功を返却する -- ユーザー登録API

ユーザー名重複チェックを実施 -- 登録済みユーザー一覧
新規ユーザーを作成する -- 新規ユーザー
保存する -- 新規ユーザー

'代替コース
ユーザー名重複チェックを実施 -down- ユーザー登録失敗を返却する
ユーザー登録失敗を返却する -up- ユーザー登録API


@enduml