@startuml

boundary ログインAPI
control ログインチェックを実施
control ログインセッションを作成する
control ログイン成功を返却する
control ログイン失敗を返却する
entity 登録済みユーザー一覧

'基本コース
ログインAPI -right- ログインチェックを実施
ログインチェックを実施 -down- ログインセッションを作成する
ログインセッションを作成する -left- ログイン成功を返却する
ログイン成功を返却する -- ログインAPI

ログインチェックを実施 -- 登録済みユーザー一覧

'代替コース
ログインチェックを実施 -down- ログイン失敗を返却する
ログイン失敗を返却する -up- ログインAPI

@enduml