@startuml

boundary ランキング表示API
control ランキング情報を取得する
control ランキング情報を返却する
entity ランキング情報

'基本コース
ランキング表示API -- ランキング情報を取得する
ランキング情報を取得する -- ランキング情報を返却する
ランキング情報を返却する -- ランキング表示API

ランキング情報を取得する -- ランキング情報
@enduml