const UN_EXPECTED_ERROR_CODE = 500;
const UN_AUTHORIZE_ERROR_CODE = 401;
const USER_NAME_MAX_LENGTH = 255;
const PASSWORD_MAX_LENGTH = 255;

export {
	UN_EXPECTED_ERROR_CODE,
	UN_AUTHORIZE_ERROR_CODE,
	USER_NAME_MAX_LENGTH,
	PASSWORD_MAX_LENGTH
};